
# PERSONALIZATION
# Site variables
name: Penn Pizza Seminar
original_repo: https://github.com/rileyshahar/pizza-seminar
description: The graduate pizza seminar in the math department at the University of Pennsylvania.
domain: rileyshahar.github.io
url: https://rileyshahar.github.io
baseurl: /pizza-seminar/


# Style variables
accent_color: "#5BC0EB"
background_color: "#FAFAFA"
footer_text_color: "#666666"

# Footer data
organizers: Chris Dunstan and Riley Shahar


# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:-0500
  TZOFFSETTO:-0400
  TZNAME:EDT
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:-0400
  TZOFFSETTO:-0500
  TZNAME:EST
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
